### ISSUE TITLE
MS JDBC Driver version

### ISSUE THREAD

**Issue by spudmcq** [goldmansachs/reladomo#158]
I see in this [closed issue](https://github.com/goldmansachs/reladomo/issues/99) that  Reladomo is certified with sqljdbc4-2.0

Where is that documented?

Can you elaborate on the bug and scope of impact in that is in the current MS JDBC driver versions? 

What is the exact version recommended?
is it the [Microsoft JDBC Driver 6.0 for SQL Server](
https://docs.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix?view=sql-server-2017)

**Comment by mohrezaei** [comment]
[This file](https://github.com/goldmansachs/reladomo/blob/master/build/reladomogs.spec) contains the driver versions. However, it's hard to decipher what those versions are, because the respective vendors mostly don't release on maven central.

MS is a bit of an oddity. sqljdbc4-2.0 works well if you want to use ```datetime```, but is a bad a choice if you want datetime2. If you have an old schema and want ```datetime```, stick with sqljdbc4-2.0, at least until these bugs ([1](https://github.com/Microsoft/mssql-jdbc/issues/493), [2](https://github.com/Microsoft/mssql-jdbc/issues/443)) are fixed. If you have a new schema, don't ever use ```datetime```. Use ```datetime2(3)``` and the newest open source 6.x driver.
