### ISSUE TITLE
Finding the "Latest" value for an entity in a Bi-Temporal Table.

### ISSUE THREAD

**Issue by spudmcq** [goldmansachs/reladomo#159]
Suppose we keep track of the contact name for an account in a bi temporal table.  At different times in history we will have different contacts associated with an account.   If the account is closed the row will be terminated in this table.
Here is an example with some data:
![exampletable](https://user-images.githubusercontent.com/7598311/40440495-4177ec94-5e8c-11e8-89aa-7ef225146457.png)

The list of the current/last contact name for every account we've ever had  (both currently open plus closed accounts)  would be:
![exampleresults](https://user-images.githubusercontent.com/7598311/40440775-fbd3b06e-5e8c-11e8-87a4-9f0440d41b55.png)

In SQL i would have to partition by Account Id,  order by valid_to desc, rank and select where  rank =1 

How should I best achieve the same result in Reladomo?

I believe the following code would work but would issue a separate findOne for each and ever distinct accountId in the table.  - Is this the way to do this or is there a better way to use the API?

```java
            List<AccountContact> listOfAccountContacts = new ArrayList<>();
            
            AggregateList aggregateList = new AggregateList(AccountContactFinder.validDate().equalsEdgePoint());
            aggregateList.addAggregateAttribute(
                "validFrom", AccountContactFinder.validDateFrom().max());
            aggregateList.addGroupBy("accountId", AccountContactFinder.accountId());
            for (AggregateData row : aggregateList)
            {
                Long accountId = row.getAttributeAsLong("accountId");
                Timestamp validFrom = row.getAttributeAsTimestamp("validFrom");
              
                
                Operation selectionOperation = AccountContactFinder.validDate().eq(validFrom);
                selectionOperation = selectionOperation.and(AccountContactFinder.account(accountId));
                AccountContact accountContact = Finder.findOne(selectionOperation);
                listOfAccountContacts.add(accountContact);
            }
```

**Comment by mohrezaei** [comment]
Two separate answers, hopefully one of them will resonate with your use case:

1) What you have can be considerably optimized with a tuple. Construct a tuple and use a tuple-in:
```java
Operation op = AccountContactFinder.validDate().equalsEdgePoint();
op = op.and(AccountContactFinder.validDateFrom().tupleWith(AccountContactFinder.account()).in(al, "validFrom", "accountId"));
```
Please note that there is a long standing unimplemented feature to do all that in a single call to the db. Right now, it'll be two selects.
2) A possibly better answer is to think carefully about your domain, specifically about the relationship between account termination and the ```terminate()``` call. If terminated accounts have a use and meaning in your domain (outside of a historical context), you might want to model that as a state, instead of using the ```terminate()``` call. Generally, in a temporal model, it's best to think of ```terminate()``` like you would a delete (outside of a historical context). If, however, this sort of query is rare and not the bread and butter of how accounts are handled, ```terminate()``` would be fine.
