### ISSUE TITLE
Building reladomo on Linux / JDK 8. Issues with  -XX:+UseSpinning jvm param

### ISSUE THREAD

**Issue by ramtej** [goldmansachs/reladomo#81]
Hi, 

**Environment** :  Ubuntu 16.04
```
Linux dvlp1 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
--
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Step:** 
$ git clone ...
$ cd reladomo
$ build/build.sh compile-reladomo

**Issue:** 
Unrecognized VM option 'UseSpinning'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comments:** 
$ grep -r "UseSpinning"

build/antbuild.sh:JVM_ARGS="-ms16m -mx2000m -server -XX:MaxPermSize=128m -XX:+UseParallelGC -XX:MaxHeapFreeRatio=20 -XX:MinHeapFreeRatio=10 -XX:CompileThreshold=100 **-XX:+UseSpinning**"

Best Regards, 
jj

**Comment by gs-rezaem** [comment]
The [BUILD.md](https://github.com/goldmansachs/reladomo/blob/master/BUILD.md) file states: Reladomo is currently built with JDK 1.6.

**Comment by ramtej** [comment]
ok, overlooked that, sorry. Any chance, that Reladomo can be built with JDK 1.8 ? Any direct reasons why JDK 1.6 is required for compilation ?

**Comment by gs-rezaem** [comment]
Backward compatibility is one of our core deliverables. We'll eventually move to 1.8, but probably not in the near future.
Building with 1.8 requires changes because the JDK sql interfaces changed. I have a [branch here](https://github.com/gs-rezaem/reladomo/tree/jdk18) that builds with 1.8, but it was just an experiment and I don't intend to keep it up to date.
Binaries are available in maven central, so as a user, there is no reason to build this yourself. If you're building because you intend to contribute, you're better off just downloading 1.6.
